import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Fragment } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Disclosure, Menu, Transition } from '@headlessui/react';
import { Bars3Icon, XMarkIcon } from '@heroicons/react/24/outline';
import { useAuth } from '../../contexts/AuthContext';
import { twMerge } from 'tailwind-merge';
const navigation = [
    { name: 'Calculator', href: '/' },
    { name: 'Saved Calculations', href: '/saved' },
    { name: 'Profile', href: '/profile' },
];
export default function DashboardLayout({ children }) {
    const { currentUser, logout } = useAuth();
    const location = useLocation();
    return (_jsxs("div", { className: "min-h-screen bg-gray-100", children: [_jsx(Disclosure, { as: "nav", className: "bg-white shadow-sm", children: ({ open }) => (_jsxs(_Fragment, { children: [_jsx("div", { className: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "flex h-16 justify-between", children: [_jsxs("div", { className: "flex", children: [_jsx("div", { className: "flex flex-shrink-0 items-center", children: _jsx("span", { className: "text-xl font-bold text-blue-600", children: "MortgageCalc" }) }), _jsx("div", { className: "hidden sm:ml-6 sm:flex sm:space-x-8", children: navigation.map((item) => (_jsx(Link, { to: item.href, className: twMerge('inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium', location.pathname === item.href
                                                        ? 'border-blue-500 text-gray-900'
                                                        : 'border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700'), children: item.name }, item.name))) })] }), _jsx("div", { className: "hidden sm:ml-6 sm:flex sm:items-center", children: _jsxs(Menu, { as: "div", className: "relative ml-3", children: [_jsx("div", { children: _jsx(Menu.Button, { className: "flex rounded-full bg-white text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2", children: _jsx("img", { className: "h-8 w-8 rounded-full", src: currentUser?.photoURL || '/default-avatar.png', alt: "" }) }) }), _jsx(Transition, { as: Fragment, enter: "transition ease-out duration-200", enterFrom: "transform opacity-0 scale-95", enterTo: "transform opacity-100 scale-100", leave: "transition ease-in duration-75", leaveFrom: "transform opacity-100 scale-100", leaveTo: "transform opacity-0 scale-95", children: _jsxs(Menu.Items, { className: "absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none", children: [_jsx(Menu.Item, { children: ({ active }) => (_jsx(Link, { to: "/profile", className: twMerge(active ? 'bg-gray-100' : '', 'block px-4 py-2 text-sm text-gray-700'), children: "Your Profile" })) }), _jsx(Menu.Item, { children: ({ active }) => (_jsx("button", { onClick: () => logout(), className: twMerge(active ? 'bg-gray-100' : '', 'block w-full text-left px-4 py-2 text-sm text-gray-700'), children: "Sign out" })) })] }) })] }) }), _jsx("div", { className: "-mr-2 flex items-center sm:hidden", children: _jsx(Disclosure.Button, { className: "inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500", children: open ? (_jsx(XMarkIcon, { className: "block h-6 w-6", "aria-hidden": "true" })) : (_jsx(Bars3Icon, { className: "block h-6 w-6", "aria-hidden": "true" })) }) })] }) }), _jsxs(Disclosure.Panel, { className: "sm:hidden", children: [_jsx("div", { className: "space-y-1 pb-3 pt-2", children: navigation.map((item) => (_jsx(Link, { to: item.href, className: twMerge('block border-l-4 py-2 pl-3 pr-4 text-base font-medium', location.pathname === item.href
                                            ? 'border-blue-500 bg-blue-50 text-blue-700'
                                            : 'border-transparent text-gray-500 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-700'), children: item.name }, item.name))) }), _jsxs("div", { className: "border-t border-gray-200 pb-3 pt-4", children: [_jsxs("div", { className: "flex items-center px-4", children: [_jsx("div", { className: "flex-shrink-0", children: _jsx("img", { className: "h-10 w-10 rounded-full", src: currentUser?.photoURL || '/default-avatar.png', alt: "" }) }), _jsxs("div", { className: "ml-3", children: [_jsx("div", { className: "text-base font-medium text-gray-800", children: currentUser?.displayName }), _jsx("div", { className: "text-sm font-medium text-gray-500", children: currentUser?.email })] })] }), _jsx("div", { className: "mt-3 space-y-1", children: _jsx("button", { onClick: () => logout(), className: "block w-full px-4 py-2 text-base font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-800", children: "Sign out" }) })] })] })] })) }), _jsx("div", { className: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8", children: children })] }));
}
